apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2
spec:
  containers:
  - name: container-pod-2
    image: nginx:latest
    ports: 
      - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"