apiVersion: v1
kind: Pod
metadata:
  name: first-pod-declarative
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      resources:
        limits:
          cpu: "1"
          memory: "500Mi"