apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    # pod information is defined here
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias-container
        image: aluracursos/portal-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: portal-configmap
        ports:
          - containerPort: 80
  replicas: 3
  # selector the pods that will be controlled by this replica set
  selector:
    matchLabels:
      app: portal-noticias
    